- hosts: aws
  become: yes
  gather_facts: no

  tasks:
   - name: authorizedkeys
     authorized_key:
       user: htidev
       state: present
       key: '{{ item }}'
     with_file:
        - /home/public_keys/01
        - /home/02
